apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-a18y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-a18y
    app.kubernetes.io/part-of: tkrw-pr714-0075-0052-app
  name: devfile-sample-a18y
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-a18y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-a18y
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0052-tenant/tkrw-pr714-0075-0052-app/devfile-sample-a18y@sha256:2f01a090a5f9b81fa3ac19d696729a31c164d92ece833a89bb59998f7604e7e0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
